cc8:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------

  #Steering----------------------------------------------------
  steering_FL_position_controller:
    type: effort_controllers/JointPositionController
    joint: steering_FL
    pid: {p: 1.0, i: 0.001, d: 0.01}
  steering_FR_position_controller:
    type: effort_controllers/JointPositionController
    joint: steering_FR
    pid: {p: 1.0, i: 0.001, d: 0.01}
  steering_RL_position_controller:
    type: effort_controllers/JointPositionController
    joint: steering_RL
    pid: {p: 1.0, i: 0.001, d: 0.01}
  steering_RR_position_controller:
    type: effort_controllers/JointPositionController
    joint: steering_RR
    pid: {p: 1.0, i: 0.001, d: 0.01}

  #Wheel_Controller--------------------------------------------
  wheel_joint_FL_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_joint_FL
    pid: {p: 1.0, i: 0.001, d: 0.01}
  wheel_joint_FR_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_joint_FR
    pid: {p: 1.0, i: 0.001, d: 0.01}
  wheel_joint_ML_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_joint_ML
    pid: {p: 1.0, i: 0.001, d: 0.01}
  wheel_joint_MR_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_joint_MR
    pid: {p: 1.0, i: 0.001, d: 0.01}
  wheel_joint_RL_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_joint_RL
    pid: {p: 1.0, i: 0.001, d: 0.01}
  wheel_joint_RR_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_joint_RR
    pid: {p: 1.0, i: 0.001, d: 0.01}

      #rocker_joint_L_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: rocker_joint_L
  #  pid: {p: 100.0, i: 0.01, d: 10.0}
    #bogie_joint_L_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: bogie_joint_L
  #  pid: {p: 100.0, i: 0.01, d: 10.0}
    #rocker_joint_R_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: rocker_joint_R
  #  pid: {p: 100.0, i: 0.01, d: 10.0}
    #bogie_joint_R_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: bogie_joint_R
  #  pid: {p: 100.0, i: 0.01, d: 10.0}

